"""
AgriBridge AI — Model Loader

Loads the six trained agent artifacts once at service startup and caches them.

Three rules this module enforces, all deliberate:

1. **The hash chain is verified before anything is deserialised.**
   ``pickle.load`` executes code embedded in the file, so a model artifact is
   equivalent to running an uploaded script. We only unpickle a file whose
   SHA-256 matches the digest recorded in ``models/agents/DIGESTS.json``, and we
   only unpickle from ``models/agents/``. A mismatch marks the agent
   unavailable — it is never a silent fallback to a fabricated score.

2. **An agent that cannot load is reported as unavailable, never as "ok".**
   ``status()`` carries the reason, and the router surfaces it verbatim.

3. **An artifact that cannot run is not "loaded".**
   A version mismatch is a *possibility*, not a verdict: a 1.7.1-fitted pickle
   read back under 1.8.0 usually reconstructs fine. So the loader does not
   quarantine on the version number alone — that would wrongly take down the
   five agents that are provably fine. Instead every loaded artifact is given
   one throwaway row through ``predict()``, and only an artifact that actually
   raises is quarantined. See :meth:`AgentModelLoader._quarantine_incompatible`.
"""
import hashlib
import json
import logging
import os
import pickle
import warnings
from pathlib import Path
from typing import Any

import pandas as pd

logger = logging.getLogger("agribridge.agents.loader")

SERVICE_ROOT = Path(__file__).resolve().parent.parent
MODEL_DIR = Path(os.getenv("AGENT_MODEL_DIR", str(SERVICE_ROOT / "models" / "agents")))
DIGEST_FILE = MODEL_DIR / "DIGESTS.json"

AGENT_NAMES = ["traceability", "quality", "spoilage", "fraud", "compliance", "trust"]


def _read_digests() -> dict[str, dict[str, Any]]:
    """
    DIGESTS.json as a mapping, read fresh each time.

    The file is tiny and is the record of truth for both the digests and the
    training scikit-learn, so it is read from disk rather than cached — a
    `write_digests()` in the same process must be visible immediately.
    """
    if not DIGEST_FILE.exists():
        return {}
    try:
        with open(DIGEST_FILE, encoding="utf-8") as f:
            return json.load(f).get("models", {})
    except Exception as exc:
        logger.error("Could not read %s: %s", DIGEST_FILE, exc)
        return {}


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


class AgentModelLoader:
    """Cache of the six agent models plus their load status."""

    def __init__(self) -> None:
        self.models: dict[str, Any] = {}
        self.status_map: dict[str, dict[str, Any]] = {}
        self.metrics: dict[str, dict[str, Any]] = {}
        self._digests: dict[str, str] = {}
        self.recorded_versions: dict[str, str] = {}
        self._recorded_training_version: str | None = None
        self._loaded = False

    # ── Digests ──────────────────────────────────────────────────────────────

    def _load_digests(self) -> dict[str, str]:
        """Recorded digests. Generated by ``python agents/generate_digests.py``."""
        return {k: v["sha256"] for k, v in _read_digests().items() if "sha256" in v}

    def _load_recorded_versions(self) -> dict[str, str]:
        """Training scikit-learn per agent, as recorded in DIGESTS.json."""
        return {k: v["sklearn_version"] for k, v in _read_digests().items() if v.get("sklearn_version")}

    def write_digests(self) -> Path:
        """
        (Re)generate DIGESTS.json from the artifacts currently on disk.

        Each entry records the scikit-learn the artifacts were trained under, so
        the loader can compare it against what the service is actually running.
        The digest step does not deserialise anything, so the version has to be
        supplied by the caller — it cannot be read off the artifact, because
        scikit-learn does not stamp itself onto an estimator (see
        :func:`_sklearn_version`).

        ``write_digests()`` with no argument records the *running* version, which
        is the honest default **only** immediately after a re-train in the same
        interpreter. Re-running it against artifacts trained elsewhere would
        overwrite the truth with the current environment, so pass
        ``--trained-on`` explicitly whenever the artifacts did not come from
        this interpreter.
        """
        recorded = self._recorded_training_version or running_sklearn()
        out: dict[str, Any] = {
            "models": {},
            "note": (
                "sklearn_version is the scikit-learn these artifacts were fitted "
                "under. The loader warns when it differs from the running version, "
                "because a pickle stores the class layout of the version that "
                "fitted it."
            ),
        }
        for name in AGENT_NAMES:
            path = MODEL_DIR / f"{name}_model.pkl"
            if not path.exists():
                continue
            out["models"][name] = {
                "sha256": _sha256(path),
                "bytes": path.stat().st_size,
            }
            if recorded:
                out["models"][name]["sklearn_version"] = recorded
        tmp = DIGEST_FILE.with_suffix(".json.tmp")
        with open(tmp, "w", encoding="utf-8") as f:
            json.dump(out, f, indent=2)
        os.replace(tmp, DIGEST_FILE)
        logger.info("Wrote digests for %d artifact(s) -> %s", len(out["models"]), DIGEST_FILE)
        return DIGEST_FILE

    # ── Loading ──────────────────────────────────────────────────────────────

    def load_all(self) -> None:
        """
        Load every agent artifact. Never raises: a failure marks that agent
        unavailable and the service still starts.
        """
        self._digests = self._load_digests()
        self.recorded_versions = self._load_recorded_versions()
        if not self._digests:
            logger.error(
                "No DIGESTS.json found. Run `python agents/generate_digests.py` — "
                "without recorded digests no artifact will be deserialised."
            )

        for name in AGENT_NAMES:
            path = MODEL_DIR / f"{name}_model.pkl"
            try:
                if not path.exists():
                    self._mark(name, False, f"artifact missing at {path}")
                    continue

                expected = self._digests.get(name)
                if expected is None:
                    self._mark(name, False, "no recorded SHA-256 digest — refusing to unpickle")
                    continue

                actual = _sha256(path)
                if actual != expected:
                    self._mark(
                        name, False,
                        f"SHA-256 mismatch (expected {expected[:12]}…, got {actual[:12]}…) — "
                        "artifact rejected, not deserialised",
                    )
                    continue

                with open(path, "rb") as f:
                    with warnings.catch_warnings(record=True) as caught:
                        warnings.simplefilter("always")
                        model = pickle.load(f)
                for w in caught:
                    logger.warning("[%s] unpickle warning: %s", name, w.message)

                self.models[name] = model
                self._mark(name, True, "")
                logger.info("✅ [%s] loaded (%s)", name, type(model).__name__)

            except Exception as exc:
                self._mark(name, False, f"{type(exc).__name__}: {exc}")
                logger.exception("Failed to load %s", name)

        self._loaded = True
        self._quarantine_incompatible()
        ok = [n for n in AGENT_NAMES if self.status_map[n]["loaded"]]
        logger.info("Agents ready: %d/%d — %s", len(ok), len(AGENT_NAMES), ", ".join(ok) or "none")

    def _mark(self, name: str, loaded: bool, reason: str) -> None:
        self.status_map[name] = {
            "agent": name,
            "loaded": loaded,
            "reason": reason,
            "algorithm": _ALGORITHMS.get(name, "unknown"),
            "artifact": str(MODEL_DIR / f"{name}_model.pkl"),
            "sklearn_version": _sklearn_version(self.models.get(name)) or self.recorded_versions.get(name),
        }

    def _check_sklearn_versions(self) -> None:
        """
        Warn when an artifact was fitted on a different scikit-learn than the
        one running.

        A pickle stores the class layout of the version that fitted it, so a
        1.7.1-fitted artifact reconstructed under 1.8.0 can carry attributes
        1.8.0 expects and 1.7.1 never set. The quality agent is exactly that
        case: it deserialises cleanly, reports as loaded, and then raises
        `AttributeError: 'SimpleImputer' object has no attribute '_fill_dtype'`
        on every request.

        This warning alone does not prevent that — it names the risk, it does
        not act on it. :meth:`_quarantine_incompatible` runs next and is what
        actually stops the broken artifact reaching a request.
        """
        running = running_sklearn()
        if not running:
            return
        for name in AGENT_NAMES:
            entry = self.status_map.get(name)
            if not entry or not entry.get("loaded"):
                continue
            trained_on = entry.get("sklearn_version")
            if not trained_on:
                logger.warning(
                    "[%s] trained on an unrecorded scikit-learn (service runs %s) — "
                    "re-run `python agents/generate_digests.py` after training so the "
                    "version is recorded, or the mismatch cannot be detected.",
                    name, running,
                )
            elif trained_on != running:
                logger.warning(
                    "[%s] trained on scikit-learn %s, service runs %s — a pickle stores "
                    "the class layout of the version that fitted it, so predictions from "
                    "this artifact may be wrong or may raise. Pin scikit-learn==%s in "
                    "requirements.txt, or re-train the artifact and re-run "
                    "`python agents/generate_digests.py`.",
                    name, trained_on, running, trained_on,
                )

    # ── Can it actually run? ─────────────────────────────────────────────────

    def _quarantine_incompatible(self) -> None:
        """
        Give every loaded artifact one throwaway row and drop the ones that raise.

        A version mismatch is a risk, not a verdict. Of the six artifacts
        fitted on 1.7.1, five reconstruct under 1.8.0 and predict correctly
        from the same loader, the same pickle module and the same class
        layout; only the quality agent's `SimpleImputer` is missing a field
        1.8.0's `transform()` dereferences. Quarantining on the version
        number alone would therefore take down five working agents to fix one
        broken one.

        So the test is behavioural, not arithmetic: build a single row routed
        the way the fitted pipeline itself routes its input, and call
        `predict()`. The value that comes back is thrown away — this is a
        liveness check, not a prediction, and nothing it returns is ever
        surfaced. What matters is only whether the call raises.

        On failure the artifact is removed from ``self.models`` and re-marked
        unavailable with the real exception, so `/api/agents/registry` and
        `run_agent` report it as down. They are never left to discover this on
        a user's request.
        """
        for name in list(self.models):
            model = self.models[name]
            try:
                _assert_predictable(model)
            except Exception as exc:
                del self.models[name]
                trained_on = self.status_map.get(name, {}).get("sklearn_version")
                running = running_sklearn()
                detail = (
                    f"artifact loads but cannot run: {type(exc).__name__}: {exc}"
                )
                if trained_on and running and trained_on != running:
                    detail += (
                        f". The artifact was fitted on scikit-learn {trained_on} and the "
                        f"service is running {running}; install the pinned version "
                        f"(scikit-learn=={trained_on}) or re-train the artifact and re-run "
                        f"`python agents/generate_digests.py`"
                    )
                self._mark(name, False, detail)
                logger.error("[%s] quarantined — %s", name, detail)
            else:
                logger.info("[%s] predict probe passed", name)

    # ── Access ───────────────────────────────────────────────────────────────

    def get(self, name: str) -> Any:
        if name not in self.models:
            reason = self.status_map.get(name, {}).get("reason") or "not loaded"
            raise AgentUnavailable(
                f"Agent '{name}' is unavailable: {reason}. "
                f"See GET /api/agents/registry for the per-agent reason."
            )
        return self.models[name]

    def is_available(self, name: str) -> bool:
        return name in self.models

    def is_loaded(self) -> bool:
        """True when the registry has been populated (agents may still be down)."""
        return self._loaded

    def available_agents(self) -> list[str]:
        return [n for n in AGENT_NAMES if n in self.models]

    def status(self) -> dict[str, Any]:
        return {
            "registryLoaded": self._loaded,
            "totalAgents": len(AGENT_NAMES),
            "availableAgents": len(self.available_agents()),
            "agents": [self.status_map[n] for n in AGENT_NAMES if n in self.status_map],
        }


class AgentUnavailable(RuntimeError):
    """Raised when a caller asks for an agent whose artifact is not loaded."""


_ALGORITHMS = {
    "traceability": "IsolationForest + deterministic rule score",
    "quality": "RandomForestRegressor",
    "spoilage": "RandomForestClassifier",
    "fraud": "RandomForestClassifier",
    "compliance": "RandomForestClassifier",
    "trust": "LogisticRegression",
}


def record_training_environment(model: Any) -> Any:
    """
    Stamp the running scikit-learn onto a fitted artifact before it is saved.

    Call this in the training script, not at load time:

        model = pipeline.fit(X, y)
        model = record_training_environment(model)
        joblib.dump(model, "quality_model.pkl")

    scikit-learn does not record its own version on an estimator, so without
    this the loader has no way to tell whether the artifact it just
    deserialised was fitted under the version now running. It is the same
    hazard the `scikit-learn==1.7.1` pin in requirements.txt guards against, and
    it is worth stamping anyway: a pin can be edited, a stamp cannot.
    """
    try:
        import sklearn
        model.sklearn_version = sklearn.__version__
    except Exception as exc:  # a frozen or slotted estimator refuses attributes
        logger.warning("Could not record the training scikit-learn: %s", exc)
    return model


def _probe_frame(model: Any) -> "pd.DataFrame":
    """
    One row shaped the way the fitted pipeline expects its input.

    Built from the pipeline's own fitted state rather than guessed:

    * ``feature_names_in_`` gives the column set and order the pipeline was
      fitted with, so a schema change is visible as a mismatch rather than
      silently reordering inputs;
    * ``ColumnTransformer.transformers_`` says which columns each sub-transformer
      takes, and a fitted ``OneHotEncoder`` carries ``categories_`` — so a
      categorical column is filled with a value the encoder has genuinely seen
      instead of one it would reject or treat as unknown;
    * everything else is ``0.0``, which every numeric transformer here
      (scaler, imputer) accepts.

    The contents are arbitrary on purpose. The row exists to make the fitted
    code path execute; nothing it predicts is kept or shown.
    """
    from sklearn.compose import ColumnTransformer

    # `is None`, never `or []`: feature_names_in_ is a numpy array, and
    # `array or []` raises "truth value of an array is ambiguous" for any
    # model that has one — which is all six of them.
    names = getattr(model, "feature_names_in_", None)
    columns = list(names) if names is not None else []

    # A fitted one-hot encoder remembers the exact category strings it saw.
    known_category: dict[str, Any] = {}
    for _, step in getattr(model, "steps", []):
        if not isinstance(step, ColumnTransformer):
            continue
        for _, transformer, routed in step.transformers_:
            categories = getattr(transformer, "categories_", None)
            if not categories or routed is None:
                continue
            for column in routed:
                known_category[column] = categories[0][0]

    row = {}
    for column in columns:
        if column in known_category:
            row[column] = pd.Series([known_category[column]], dtype=object)
        else:
            row[column] = pd.Series([0.0], dtype=float)
    return pd.DataFrame(row, columns=columns)


def _assert_predictable(model: Any) -> None:
    """
    Run one prediction, discarding the result. Raises if the artifact cannot.

    Reached only for an artifact that already passed its SHA-256 gate and
    deserialised, so the only thing left to establish is whether the fitted
    code path still runs under this scikit-learn.

    A model that is not a fitted pipeline has no ``predict`` to call and cannot
    be checked; that is not a failure, and it is not treated as one.
    """
    if not hasattr(model, "predict"):
        logger.debug("Artifact has no predict(); skipping the runnability probe")
        return
    model.predict(_probe_frame(model))


def _sklearn_version(model: Any) -> str | None:
    """
    The scikit-learn an artifact was fitted on, when the artifact recorded it.

    scikit-learn does **not** stamp its version onto estimators. `sklearn_version`
    is not an attribute of `BaseEstimator` and is not set by `fit`, so there is
    nothing to unwrap to and no place in a fitted pipeline where the training
    version survives. (An earlier version of this function walked
    `Pipeline.steps` looking for one; it returned None for all six artifacts,
    because the attribute does not exist rather than because it was nested.)

    So the version is recorded where it can actually be observed, and read from
    there:

    1. an attribute on the artifact, for anything trained via
       :func:`record_training_environment` — the one supported way to write a
       new artifact;
    2. `sklearn_version` in `DIGESTS.json`, for the six artifacts currently on
       disk, which predate that helper;
    3. otherwise None, and the registry reports it as unknown rather than
       quietly assuming it matches.
    """
    if model is None:
        return None
    return getattr(model, "sklearn_version", None) or None


def trained_on_sklearn(name: str) -> str | None:
    """The recorded training scikit-learn for one agent, from DIGESTS.json."""
    return _read_digests().get(name, {}).get("sklearn_version")


def running_sklearn() -> str | None:
    """The scikit-learn the service itself is running. None if not installed."""
    try:
        import sklearn
        return sklearn.__version__
    except Exception:
        return None
