import { NextRequest } from 'next/server';
import { findBatchByIdOrCode } from '@/lib/db/repositories/batches';
import { createManyTemperatureLogs } from '@/lib/db/repositories/iot';
import { requireAuth } from '@/lib/auth';
import { successResponse, errorResponse } from '@/lib/response';

// ─── GET /api/iot/simulator/start ─────────────────────────────────────────────
// Generates a batch of simulated IoT readings for a given batch.
// CLEARLY IDENTIFIED AS SIMULATED — never presented as real sensor data.

export async function POST(req: NextRequest) {
    const authResult = await requireAuth(req, ['TRANSPORTER', 'FARMER', 'EXPORTER', 'ADMIN']);
    if (authResult instanceof Response) return authResult;

    try {
        const body = await req.json();
        const { batchId, shipmentId, hoursOfData = 24, intervalMinutes = 30 } = body;

        if (!batchId && !shipmentId) {
            return errorResponse('Either batchId or shipmentId is required', 'VALIDATION_ERROR', 400);
        }

        // Resolve batchId
        let resolvedBatchId: string | undefined;
        if (batchId) {
            const batch = await findBatchByIdOrCode(batchId);
            if (!batch) return errorResponse(`Batch ${batchId} not found`, 'BATCH_NOT_FOUND', 404);
            resolvedBatchId = batch._id;
        }

        // Generate realistic cold-chain data
        // Typical reefer container: target 12°C, slight drift and occasional spike
        const readings = [];
        const now = Date.now();
        const totalReadings = Math.floor((hoursOfData * 60) / intervalMinutes);
        const baseTemp = 12.0;
        const baseHumidity = 75.0;

        let tempDrift = 0;
        let humidityDrift = 0;

        for (let i = 0; i < totalReadings; i++) {
            const timestamp = new Date(now - (totalReadings - i) * intervalMinutes * 60 * 1000);

            // Simulate realistic temperature drift (random walk, bounded)
            tempDrift += (Math.random() - 0.5) * 0.8;
            tempDrift = Math.max(-3.0, Math.min(3.0, tempDrift));

            humidityDrift += (Math.random() - 0.5) * 2;
            humidityDrift = Math.max(-10, Math.min(10, humidityDrift));

            // Occasional spike (port loading, door opening)
            const spike = Math.random() < 0.05 ? (Math.random() * 5 + 2) : 0;

            const temperature = Math.round((baseTemp + tempDrift + spike) * 100) / 100;
            const humidity = Math.round((baseHumidity + humidityDrift) * 100) / 100;

            readings.push({
                batchId: resolvedBatchId,
                shipmentId,
                sensorId: `SIM-${resolvedBatchId?.slice(-6) || shipmentId?.slice(-6)}`,
                temperature,
                humidity,
                location: body.location || 'Reefer Container (Simulated)',
                isSimulated: true,
                timestamp,
            });
        }

        // Batch insert. The repository returns the count directly; `insertMany`
        // itself resolves to the array of inserted documents, and reaching for
        // `.count` on that is what would have made this field `undefined`.
        const readingsCreated = await createManyTemperatureLogs(readings);

        return successResponse(
            {
                message: '⚠️ SIMULATED DATA — Not from physical sensor',
                batchId: resolvedBatchId,
                readingsCreated,
                hoursOfData,
                intervalMinutes,
                notice: 'This data was generated by the AgriBridge IoT Simulator for testing/demonstration purposes only.',
            },
            201
        );
    } catch (error: unknown) {
        console.error('Simulator error:', error);
        return errorResponse('Failed to generate simulated readings', 'SERVER_ERROR', 500);
    }
}
